### ISSUE TITLE
Ads shows only on first page load

### ISSUE THREAD

**Issue by boateng-ampaw** [shriekdj/nextjs13_google_adsense#2]
Thank you for your google adsense package. I am suing the package in Next js 14 and everything works fine except it only works on first page load. I have it installed on the home page (/app/page.js). However, when I navigate away from the home page and come page, the Ads do no show anymore.

**Comment by shriekdj** [comment]
yeah @boateng-ampaw , currently this code only work when we add component files directly, and not working by bundling to package maybe because of webpack.
you can just copy these 2 files in your project they are only near 25 lines long component.
like below
`/components/GoogleAdUnitClient.tsx`

```tsx
'use client';
import React from 'react';
import { usePathname, useSearchParams } from 'next/navigation';

export type GoogleAdUnitProps = {
  children: React.ReactNode;
};

declare global {
  interface Window {
    adsbygoogle?: any | any[];
  }
}

const GoogleAdUnitClient: React.FC<GoogleAdUnitProps> = ({ children }) => {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  React.useEffect(() => {
    try {
      (window.adsbygoogle = window.adsbygoogle || []).push({});
    } catch (err) {
      console.error(err);
    }
  }, [pathname, searchParams]);
  return <React.Fragment>{children}</React.Fragment>;
};

export default GoogleAdUnitClient;
```

And 2nd File
`/components/GoogleAdUnit.tsx`

```tsx
import React, { Suspense } from 'react';
import GoogleAdUnitClient, { GoogleAdUnitProps } from './GoogleAdUnitClient';

// const GoogleAdUnitClient = React.lazy(() => import('./GoogleAdUnitClient'))

const GoogleAdUnit = ({ children }: GoogleAdUnitProps) => {
  return (
    <Suspense fallback={null}>
      <GoogleAdUnitClient>{children}</GoogleAdUnitClient>
    </Suspense>
  );
};

export default GoogleAdUnit;
```

Directly copy paste this files in your project and import the 2nd component wherever you want,

**Comment by shriekdj** [comment]
this code is for app router but if you are using `pages` router you can use any nextjs adsense package if you want

**Comment by johosz** [comment]
Thank you very much for the code you provided; it has been extremely useful. I appreciate your help!

**Comment by shriekdj** [comment]
No Problem @johosz  😊 .
